name: Bug/Error Found in the Guide?
description: Issues are only opened on GitHub by one of the team members after we have confirmed them on our Discord server. Issues raised directly on GitHub will be automatically closed.
title: "[Bug]"
labels: ["Type: Bug", "Status: Triage Needed"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Discord
      description: By submitting this issue, you agree that you have visited the Discord server and that a team member confirmed this issue.
      options:
        - label: I visited the Discord server, and one of the team members confirmed this issue.
          required: true
  - type: markdown
    attributes:
      value: "## Which Guide"
  - type: checkboxes
    attributes:
      label: Guide Name
      description: Please select the Guide(s) in which you found a bug or an error.
      options:
        - label: Bazarr
        - label: Downloaders/Deluge
        - label: Downloaders/NZBGet
        - label: Downloaders/Other
        - label: Downloaders/Qbittorrent
        - label: Downloaders/ruTorrent
        - label: Downloaders/SABnzbd
        - label: File and Folder Structure (aka Hardlinks)
        - label: File and Folder Structure (aka Hardlinks)/Docker
        - label: File and Folder Structure (aka Hardlinks)/Dockstarter
        - label: File and Folder Structure (aka Hardlinks)/Native
        - label: File and Folder Structure (aka Hardlinks)/Synology
        - label: File and Folder Structure (aka Hardlinks)/TrueNAS-Core
        - label: File and Folder Structure (aka Hardlinks)/Unraid
        - label: File and Folder Structure (aka Hardlinks)/Windows
        - label: Guide-Sync
        - label: Misc
        - label: Other
        - label: Plex
        - label: Prowlarr
        - label: Radarr
        - label: Sonarr
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can add image URLs or use any other method to display the screenshot (provided GitHub supports it).
      placeholder: Add screenshot...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Add context...
    validations:
      required: false
