name: Request a Guide
description: Request a Guide here (This is only for new Guide requests, not for changes to existing guides, custom formats etc, if you are unsure please check out the Discord server first.)
title: "[Request]"
labels: ["Type: Guide Request", "Status: Triage Needed"]
body:
  - type: input
    id: application
    attributes:
      label: For which application would like to see this Guide?
      description: Radarr / Sonarr / Bazarr / etc
      placeholder: Enter the application name here
  - type: textarea
    id: guide_description
    attributes:
      label: Describe what you would like to see in the Guide
      description: A clear and concise description of what you want to see in the Guide
      placeholder: Enter a brief description here
    validations:
      required: true
