name: Label Conflicts

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "Status: Conflicted"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
