name: Label Conflicts

on:
  push:
    branches: [master]
  # pull_request_target is safe here; this workflow never checks out PR code.
  pull_request_target:
    types: [synchronize]

jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    permissions:
      pull-requests: write
    steps:
      - name: Label merge conflicts
        uses: eps1lon/actions-label-merge-conflict@1df065ebe6e3310545d4f4c4e862e43bdca146f0 # v3.0.3
        with:
          dirtyLabel: "Status: Conflicted"
          repoToken: ${{ secrets.GITHUB_TOKEN }}
