name: Lint - EditorConfig

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  editorconfig-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: editorconfig-checker
        run: |
          docker run --rm \
            -v "${GITHUB_WORKSPACE}":/check \
            mstruebing/editorconfig-checker
