name: Validate Quality Profiles

on:
  push:
    paths:
      - .github/workflows/quality-profile-validation.yml
      - docs/json/radarr/cf/*.json
      - docs/json/radarr/quality-profiles/**
      - docs/json/radarr/quality-profile-groups/**
      - docs/json/radarr/cf-groups/**
      - docs/json/sonarr/cf/*.json
      - docs/json/sonarr/quality-profiles/**
      - docs/json/sonarr/quality-profile-groups/**
      - docs/json/sonarr/cf-groups/**
      - scripts/validate-quality-profiles.py
  pull_request:
    paths:
      - .github/workflows/quality-profile-validation.yml
      - docs/json/radarr/cf/*.json
      - docs/json/radarr/quality-profiles/**
      - docs/json/radarr/quality-profile-groups/**
      - docs/json/radarr/cf-groups/**
      - docs/json/sonarr/cf/*.json
      - docs/json/sonarr/quality-profiles/**
      - docs/json/sonarr/quality-profile-groups/**
      - docs/json/sonarr/cf-groups/**
      - scripts/validate-quality-profiles.py

jobs:
  validate-quality-profiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Validate quality profiles
        run: python scripts/validate-quality-profiles.py
