name: Validate Quality Profiles

on:
  push:
    paths:
      - .github/workflows/quality-profile-validation.yml
      - docs/json/radarr/cf/*.json
      - docs/json/radarr/quality-profiles/**
      - docs/json/radarr/quality-profile-groups/**
      - docs/json/radarr/cf-groups/**
      - docs/json/sonarr/cf/*.json
      - docs/json/sonarr/quality-profiles/**
      - docs/json/sonarr/quality-profile-groups/**
      - docs/json/sonarr/cf-groups/**
      - scripts/validate-quality-profiles.py
  pull_request:
    paths:
      - .github/workflows/quality-profile-validation.yml
      - docs/json/radarr/cf/*.json
      - docs/json/radarr/quality-profiles/**
      - docs/json/radarr/quality-profile-groups/**
      - docs/json/radarr/cf-groups/**
      - docs/json/sonarr/cf/*.json
      - docs/json/sonarr/quality-profiles/**
      - docs/json/sonarr/quality-profile-groups/**
      - docs/json/sonarr/cf-groups/**
      - scripts/validate-quality-profiles.py

permissions:
  contents: read

jobs:
  validate-quality-profiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Validate quality profiles
        run: python scripts/validate-quality-profiles.py
