name: Trigger PR Build

on:
  pull_request:

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Filter rendered content changes
        id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            rendered:
              - 'docs/**'
              - 'images/**'
              - 'includes/**'
              - 'overrides/**'
              - 'mkdocs.yml'

      - name: Save PR info
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
          SHOULD_DEPLOY: ${{ steps.filter.outputs.rendered }}
        run: |
          mkdir -p ./pr_info
          echo "$PR_NUMBER" > ./pr_info/PR_NUMBER
          echo "$PR_SHA" > ./pr_info/PR_SHA
          echo "$SHOULD_DEPLOY" > ./pr_info/SHOULD_DEPLOY

      - name: Upload PR info
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pr_info
          path: pr_info/
